---
- name: Install OpenVPN
  apt: name=openvpn={{openvpn_version}} state=present update_cache=yes
  tags:
    - install

- name: Install OpenSSL
  apt: pkg=openssl state=present

- name: Generate config file
  template: src=etc/openvpn/openvpn.conf.j2 dest=/etc/openvpn/client.conf
  notify:
    - restart openvpn
  tags:
    - config

- name: Start OpenVPN
  service: name=openvpn state=started enabled=yes
  tags:
    - openvpn